AllCops:
 NewCops: enable
 Exclude:
 - 'db//*'
 - 'config//*'
 - 'script//*'
 - 'bin//*'
 - 'test/**/*'
 - 'Gemfile'
 - 'Gemfile.lock'
 - 'config.ru'

Style/Documentation:
 Enabled: false
Style/FrozenStringLiteralComment:
 Enabled: false
