require:
 - rubocop-rails
 - rubocop-rspec

AllCops:
 NewCops: enable
 Exclude:
 - 'db/**/*'
 - 'config/**/*'
 - 'bin/**/*'
 - 'spec/**/*'
 - 'node_modules/**/*'
 - 'tmp/**/*'
 - 'vendor/**/*'
 - '.git/**/*'
 - 'Gemfile'
 - 'Rakefile'
 - 'Gemfile.lock'
 - 'config.ru'

Style/Documentation:
 Enabled: false
Style/FrozenStringLiteralComment:
 Enabled: false
