require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'config/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'lib/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'Gemfile.lock'
    - 'config.ru'

inherit_from:
  - .rubocop_airbnb.yml

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
